Natives work

diff --git a/makeutils/DimacsTest b/makeutils/DimacsTest
--- a/makeutils/DimacsTest
+++ b/makeutils/DimacsTest
@@ -13,12 +13,12 @@ n=${#TESTLIST[*]}
 for ((i=0;i<n;i++)); do
   test=${TESTLIST[i]}
   status=${STATUSLIST[i]}
-  echo "$test" 
+  echo "  $test" 
   echo "$test:" >> $LOGFILE
-  time $SATSOLVER_BIN $QUERY_PATH/$test.dimacs \
-    | ./FormatDimacs $QUERY_PATH/$test.tmpl > $test.fmtout 2>> $LOGFILE
+  (time $SATSOLVER_BIN $QUERY_PATH/$test.dimacs) 2>> $LOGFILE \
+    | ./FormatDimacs $QUERY_PATH/$test.tmpl > $test.fmtout
   cat $test.fmtout >> $LOGFILE
-  head -n 1 $test.fmtout | grep -q "^$status" || exit 1
+  head -n 1 $test.fmtout | grep -q "^$status" || echo "    Test failed"
   rm $test.fmtout
 done
 
diff --git a/makeutils/GcilTest b/makeutils/GcilTest
--- a/makeutils/GcilTest
+++ b/makeutils/GcilTest
@@ -13,7 +13,7 @@ n=${#TESTLIST[*]}
 for ((i=0;i<n;i++)); do
   test=${TESTLIST[i]}
   succ=${SUCCESSLIST[i]}
-  echo "$test" 
+  echo "  $test"
   echo "$test:" >> $LOGFILE
   DIR=`pwd`
   cd $GCPARSER_PATH
@@ -21,7 +21,7 @@ for ((i=0;i<n;i++)); do
   # Sometimes this leaves Java processes hanging in the background FIXME
   $RDIR/runopt $DIR/$CIRCUIT_PATH/$test.cir $DIR/$CIRCUIT_PATH/$test-server.in \
                $DIR/$CIRCUIT_PATH/$test-client.in 2>> $DIR/$LOGFILE
-  grep -q "$succ = 1" results/siserverout || exit 1
+  grep -q "$succ = 1" results/siserverout || echo "    Test failed"
   cd $DIR
 done
 
